-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema main
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main` DEFAULT CHARACTER SET utf8 ;
USE `main` ;

-- -----------------------------------------------------
-- Table `main`.`admcat_acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admcat_acciones` (
  `IDACCION` INT(11) NOT NULL,
  `ACCNOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `ACCDESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDACCION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admcat_entidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admcat_entidades` (
  `IDENTIDAD` INT(11) NOT NULL,
  `ENTNOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `ENTDESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  `ENTFECHA` DATETIME NULL DEFAULT NULL,
  `ENTESTADO` TINYINT(1) NULL DEFAULT NULL,
  `LOGREG_IDUSUARIOCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDUSUARIOMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_FECHACREA` DATETIME NULL DEFAULT NULL,
  `LOGREG_FECHAMODIFICA` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`IDENTIDAD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admcat_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admcat_modulo` (
  `IDMODULO` INT(11) NOT NULL,
  `MODNOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `MODDESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDMODULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admcat_funcionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admcat_funcionalidades` (
  `IDFUNCIONALIDAD` INT(11) NOT NULL,
  `IDMODULO` INT(11) NOT NULL,
  `FUNNOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `FUNDESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDFUNCIONALIDAD`),
  INDEX `FK_ADMCAT_MODULO_TO_ADMCAT_FUNCIONALIDADES` (`IDMODULO` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_MODULO_TO_ADMCAT_FUNCIONALIDADES`
    FOREIGN KEY (`IDMODULO`)
    REFERENCES `main`.`admcat_modulo` (`IDMODULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admcat_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admcat_roles` (
  `IDROL` INT(11) NOT NULL,
  `ROLNOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `ROLDESCRIPCION` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`IDROL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admcat_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admcat_usuarios` (
  `IDUSUARIO` INT(11) NOT NULL,
  `IDENTIDAD` INT(11) NOT NULL,
  `USUNOMBRE` VARCHAR(255) NULL DEFAULT NULL,
  `USUCORREO` VARCHAR(255) NULL DEFAULT NULL,
  `USUCONTRASENA` VARCHAR(255) NULL DEFAULT NULL,
  `USUFECHA` DATETIME NULL DEFAULT NULL,
  `USUESTADO` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`IDUSUARIO`),
  INDEX `FK_ADMCAT_ENTIDADES_TO_ADMCAT_USUARIOS` (`IDENTIDAD` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_ENTIDADES_TO_ADMCAT_USUARIOS`
    FOREIGN KEY (`IDENTIDAD`)
    REFERENCES `main`.`admcat_entidades` (`IDENTIDAD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admrel_accfun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admrel_accfun` (
  `IDACCION` INT(11) NOT NULL,
  `IDFUNCIONALIDAD` INT(11) NOT NULL,
  `IDACCFUN` INT(11) NOT NULL,
  PRIMARY KEY (`IDACCFUN`),
  INDEX `FK_ADMCAT_ACCIONES_TO_ADMREL_ACCFUN` (`IDACCION` ASC) VISIBLE,
  INDEX `FK_ADMCAT_FUNCIONALIDADES_TO_ADMREL_ACCFUN` (`IDFUNCIONALIDAD` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_ACCIONES_TO_ADMREL_ACCFUN`
    FOREIGN KEY (`IDACCION`)
    REFERENCES `main`.`admcat_acciones` (`IDACCION`),
  CONSTRAINT `FK_ADMCAT_FUNCIONALIDADES_TO_ADMREL_ACCFUN`
    FOREIGN KEY (`IDFUNCIONALIDAD`)
    REFERENCES `main`.`admcat_funcionalidades` (`IDFUNCIONALIDAD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admrel_accfunrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admrel_accfunrol` (
  `IDACCFUNROL` INT(11) NOT NULL,
  `IDACCION` INT(11) NOT NULL,
  `IDFUNCIONALIDAD` INT(11) NOT NULL,
  `IDROL` INT(11) NOT NULL,
  `ROLFUNPERMISOS` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`IDACCFUNROL`),
  INDEX `FK_ADMCAT_ACCIONES_TO_ADMREL_ACCFUNROL` (`IDACCION` ASC) VISIBLE,
  INDEX `FK_ADMCAT_ROLES_TO_ADMREL_ACCFUNROL` (`IDROL` ASC) VISIBLE,
  INDEX `FK_ADMCAT_FUNCIONALIDADES_TO_ADMREL_ACCFUNROL` (`IDFUNCIONALIDAD` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_ACCIONES_TO_ADMREL_ACCFUNROL`
    FOREIGN KEY (`IDACCION`)
    REFERENCES `main`.`admcat_acciones` (`IDACCION`),
  CONSTRAINT `FK_ADMCAT_FUNCIONALIDADES_TO_ADMREL_ACCFUNROL`
    FOREIGN KEY (`IDFUNCIONALIDAD`)
    REFERENCES `main`.`admcat_funcionalidades` (`IDFUNCIONALIDAD`),
  CONSTRAINT `FK_ADMCAT_ROLES_TO_ADMREL_ACCFUNROL`
    FOREIGN KEY (`IDROL`)
    REFERENCES `main`.`admcat_roles` (`IDROL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`admrel_rolusu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`admrel_rolusu` (
  `IDROLUSUARIO` INT(11) NOT NULL,
  `IDROL` INT(11) NOT NULL,
  `IDUSUARIO` INT(11) NOT NULL,
  PRIMARY KEY (`IDROLUSUARIO`),
  INDEX `FK_ADMCAT_ROLES_TO_ADMREL_ROLUSU` (`IDROL` ASC) VISIBLE,
  INDEX `FK_ADMCAT_USUARIOS_TO_ADMREL_ROLUSU` (`IDUSUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_ROLES_TO_ADMREL_ROLUSU`
    FOREIGN KEY (`IDROL`)
    REFERENCES `main`.`admcat_roles` (`IDROL`),
  CONSTRAINT `FK_ADMCAT_USUARIOS_TO_ADMREL_ROLUSU`
    FOREIGN KEY (`IDUSUARIO`)
    REFERENCES `main`.`admcat_usuarios` (`IDUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_accfun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_accfun` (
  `IDACCFUN` INT(11) NOT NULL,
  `LOGREG_IDACCFUNCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDACCFUNMODIFICA` INT(11) NULL DEFAULT NULL,
  INDEX `FK_ADMREL_ACCFUN_TO_LOGREG_ACCFUN` (`IDACCFUN` ASC) VISIBLE,
  CONSTRAINT `FK_ADMREL_ACCFUN_TO_LOGREG_ACCFUN`
    FOREIGN KEY (`IDACCFUN`)
    REFERENCES `main`.`admrel_accfun` (`IDACCFUN`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_accfunrol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_accfunrol` (
  `IDACCFUNROL` INT(11) NOT NULL,
  `LOGREG_IDACCFUNROLCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDACCFUNROLMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_ROLFUNPERMISOSCREA` TINYINT(1) NULL DEFAULT NULL,
  `LOGREG_ROLFUNPERMISOSMODIFICA` TINYINT(1) NULL DEFAULT NULL,
  INDEX `FK_ADMREL_ACCFUNROL_TO_LOGREG_ACCFUNROL` (`IDACCFUNROL` ASC) VISIBLE,
  CONSTRAINT `FK_ADMREL_ACCFUNROL_TO_LOGREG_ACCFUNROL`
    FOREIGN KEY (`IDACCFUNROL`)
    REFERENCES `main`.`admrel_accfunrol` (`IDACCFUNROL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_acciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_acciones` (
  `IDACCION` INT(11) NOT NULL,
  `LOGREG_IDACCIONCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDACCIONMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_ACCNOMBRECREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_ACCNOMBREMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_ACCDESCRIPCIONCREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_ACCDESCRIPCIONMODIFICA` VARCHAR(255) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_funcionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_funcionalidades` (
  `IDFUNCIONALIDAD` INT(11) NOT NULL,
  `LOGREG_IDFUNCIONALIDADCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDFUNCIONALIDADMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_FUNNOMBRECREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_FUNNOMBREMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_FUNDESCRIPCIONCREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_FUNDESCRIPCIONMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_ADMCAT_FUNCIONALIDADES_TO_LOGREG_FUNCIONALIDADES` (`IDFUNCIONALIDAD` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_FUNCIONALIDADES_TO_LOGREG_FUNCIONALIDADES`
    FOREIGN KEY (`IDFUNCIONALIDAD`)
    REFERENCES `main`.`admcat_funcionalidades` (`IDFUNCIONALIDAD`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_modulo` (
  `IDMODULO` INT(11) NOT NULL,
  `LOGREG_IDMODULOCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDMODULOMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_MODNOMBRECREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_MODNOMBREMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_MODDESCRIPCIONCREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_MODDESCRIPCIONMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_ADMCAT_MODULO_TO_LOGREG_MODULO` (`IDMODULO` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_MODULO_TO_LOGREG_MODULO`
    FOREIGN KEY (`IDMODULO`)
    REFERENCES `main`.`admcat_modulo` (`IDMODULO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_roles` (
  `IDROL` INT(11) NOT NULL,
  `LOGREG_IDROLCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDROLMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_ROLNOMBRECREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_ROLNOMBREMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_ROLDESCRIPCIONCREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_ROLDESCRIPCIONMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK_ADMCAT_ROLES_TO_LOGREG_ROLES` (`IDROL` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_ROLES_TO_LOGREG_ROLES`
    FOREIGN KEY (`IDROL`)
    REFERENCES `main`.`admcat_roles` (`IDROL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_rolusu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_rolusu` (
  `IDROLUSUARIO` INT(11) NOT NULL,
  `LOGREG_IDROLUSUARIOCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDROLUSUARIOMODIFICA` INT(11) NULL DEFAULT NULL,
  INDEX `FK_ADMREL_ROLUSU_TO_LOGREG_ROLUSU` (`IDROLUSUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_ADMREL_ROLUSU_TO_LOGREG_ROLUSU`
    FOREIGN KEY (`IDROLUSUARIO`)
    REFERENCES `main`.`admrel_rolusu` (`IDROLUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `main`.`logreg_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `main`.`logreg_usuarios` (
  `IDUSUARIO` INT(11) NOT NULL,
  `LOGREG_IDUSUARIOCREA` INT(11) NULL DEFAULT NULL,
  `LOGREG_IDUSUARIOMODIFICA` INT(11) NULL DEFAULT NULL,
  `LOGREG_USUNOMBRECREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_USUNOMBREMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_USUCORREOCREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_USUCORREOMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_USUCONTRASENACREA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_USUCONTRASENAMODIFICA` VARCHAR(255) NULL DEFAULT NULL,
  `LOGREG_USUFECHACREA` DATETIME NULL DEFAULT NULL,
  `LOGREG_USUFECHAMODIFICA` DATETIME NULL DEFAULT NULL,
  `LOGREG_USUESTADOCREA` VARCHAR(50) NULL DEFAULT NULL,
  `LOGREG_USUESTADOMODIFICA` VARCHAR(50) NULL DEFAULT NULL,
  INDEX `FK_ADMCAT_USUARIOS_TO_LOGREG_USUARIOS` (`IDUSUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_ADMCAT_USUARIOS_TO_LOGREG_USUARIOS`
    FOREIGN KEY (`IDUSUARIO`)
    REFERENCES `main`.`admcat_usuarios` (`IDUSUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
